language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: share-you-idea-ec
  api_key:
    secure: QAJmjPRf9wVUhNvEZQkz6sf/so3XDPGlz5QQ1CERggUDIYkmtktdc0eL9l7Yucl4t2l2Ur+FbNG5VYaN+q3v2cntaZOmK7LR/aKNfl8r+bk8QinUjfqVX5MemYE+ZhlOFzVXKm8EDQF4DfAfnlhBByAbasInS89iuxz5I0Ort2xFnf9c7+d2Qw4OeW6CeSzLF1bgnN2lLetXlpXhKRpT7RhKwt/lZWYbaJUJQrn2ZlGU5tUZcwOvI6620DPtzKa2honBavpsY/v/i8oeatX5Epp80WCHFa3KGd1T1oW1lPZBwVO2bcWo1tWUhnsqcZoE1r+zK4Q1USfd7c7sVF3/XTT9MmTCthI3dj+bdyWJvXzUV8+PmKwXg2qkavzdM6pT9SNhRyYfkCiXpcOmQ0h+MDxt9IIBxpsfvwASPCjjMHzOB7tAfe3/JEiFPgvhhDLUB2bEVctgHtBzjRhvMapM/zvfi337zfet0DKnRHB6FbxW6ckYz/faAb8XUQpNu3ZYLAPWS+A9W3IE67G+GU/DflTAqnrpqhPmpigH5O5pj7JAUY6Kt1r4LE6fTnKZKozLeKbon6Ro61A1txkb1ncdBwx1Q1fwGSqV6MKTVTyVsQr8TG+XpIuyZFLF+Q4Oj5CZIYt3AJHnLhAWNKSUWt4tvQh9kGJOO3IUnFb5jkKp358=
